### ISSUE TITLE
a little type in sample code

### ISSUE THREAD

**Issue by abbaspalash** [vinzenz/vsqlite--#20]
Hi
First thing first, thank you so much for sharing your efforts

I think there is just a little typo in given sample code
line
    sqlite::execute insert(con, "INSERT INTO TEST VALUE(?, ?);");
should be
    sqlite::execute ins(con, "INSERT INTO TEST VALUES(?, ?);");

**Comment by vinzenz** [comment]
Thank you for reporting.
I have fixed it on the web, I guess this is where you have found it.

**Comment by abbaspalash** [comment]
Yes, you are right
actually it seems it's my typo!

**Comment by vinzenz** [comment]
No it wasn't your typo. ;-) I just fixed it on the website. The website had it wrong exactly like you posted it :-)
