### ISSUE TITLE
Typos in the website example code

### ISSUE THREAD

**Issue by yukipyon** [vinzenz/vsqlite--#25]
Hello, I very much like your library and would like to bring an issue to your attention.

There appears to be two typos in the example code on the project's website.
http://vsqlite.virtuosic-bytes.com/

The first is `execption` instead of `exception`. The other is `VALUE` instead of `VALUES` in the prepared SQL statement. 

I hope this helps.

**Comment by vinzenz** [comment]
Sorry for the delay I finally fixed that issue
