### ISSUE TITLE
Packages for Slackware

### ISSUE THREAD

**Issue by gdsotirov** [vinzenz/vsqlite--#29]
This is just to make you aware that I'm building 32 and 64 bit packages of vsqlite-- for [Slackware Linux](http://slackware.com/). They could be found on my site SlackPack at [this URL](http://sotirov-bg.net/slackpack/search.cgi?q=vsqlite) and if you consider you could add a reference in ["Install with package manager" section](http://vsqlite.virtuosic-bytes.com/#vsqlite%2D%2D%2Dinstall) of the site.

**Comment by vinzenz** [comment]
Done 

👍  Thanks for letting me know and building those packages
